version: '2'
services:
  alpine_ocserv:
    #build: .
    image: alpine_ocserv
    privileged: true
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./certs:/etc/ocserv/certs
    - /etc/letsencrypt/live/[DOMAIN]/fullchain.pem:/etc/ocserv/certs/server-cert.pem:ro
    - /etc/letsencrypt/live/[DOMAIN]/privkey.pem:/etc/ocserv/certs/server-key.pem:ro
    ports:
    - 60443:443
    - 60443:443/udp
    environment:
    - NO_TEST_USER=1
    - CA_CN=CA
    - CA_ORG=Corp
    - CA_DAYS=9999
    - SRV_CN=[DOMAIN]
    - SRV_ORG=Company
    - SRV_DAYS=9999
    - VPS_SERVER_IP=
    - VPS_SS_PORT=
    - VPS_SS_PASSWORD=
    - VPS_SS_METHOD=
    - SUB_NETWORK=192.168.128.0
    - SS_REDIR_PORT=65500
