version: '2'
services:
  alpine_ocserv:
    build: .
    privileged: true
    restart: always
    ports:
    - 60443:443
    volumes:
    - ./cert/server-cert.pem:/etc/ocserv/server-cert.pem
    - ./cert/server-key.pem:/etc/ocserv/server-key.pem
    environment:
    - NO_TEST_USER=1
