version: '2'
services:
  alpine_ocserv:
    #build: .
    image: alpine_ocserv
    privileged: true
    restart: always
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ./certs:/etc/ocserv/certs
    - /etc/letsencrypt/live/[DOMAIN]/cert.pem:/etc/ocserv/certs/server-cert.pem:ro
    - /etc/letsencrypt/live/[DOMAIN]/privkey.pem:/etc/ocserv/certs/server-key.pem:ro
    ports:
    - 60443:443
    - 60443:443/udp
    environment:
    - NO_TEST_USER=1
